database_prod:
  dbname: "db_mysql"
  dbtable: "music"
database_test:
  dbname: "db_mysql"
  dbtable: "music"

# service_type should be NodePort, ClusterIP or LoadBalancer
service_type: NodePort
replicas: 1

image:
  repository: 
  tag: "red"

pod:
  target_port: 8000
  port: 80

serviceMonitor:
  enabled: true
  labels:
    release: kube-prometheus-stack
    app: monitoring
  interval: "30s"
  path: "/metrics"
