{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- toYaml .Values.serviceMonitor.labels | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  endpoints:
    - port: {{ .Values.serviceMonitor.port | default http }}
      interval: {{ .Values.serviceMonitor.interval | default "30s" }}
      path: {{ .Values.serviceMonitor.path | default "/metrics" }}
{{- end }}
